version: '3'
services:
  web:
    build: .
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec foreman start"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
      - "3035:3035"
    networks: 
      - "default"
