version: '3'
services:
  webpack-dev-server:
    build: .
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: bin/webpack-dev-server
    volumes:
      - .:/myapp
    ports: 
      - "3035:3035"
    networks: 
      - "default"
  web:
    build: .
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack-dev-server
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    networks: 
      - "default"
